version: "3.9"

include:
  - ciphertrust.yaml
  - postgres.yaml
services:
  app:
    build: .
    container_name: evaultz
    depends_on:
      - db
      - ciphertrust
    env_file:
      - .env
    ports:
      - "8082:8082"
    develop:
      watch:
        - action: sync
          path: .
          target: /app

volumes:
  db_data:
