include:
  - postgres.yaml

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: evaultz-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app:delegated # mount source for hot reload
      - backend_tmp:/app/tmp # Air build output
      - go_cache:/go/pkg/mod # cache Go modules
    ports:
      - "8082:8082"
    networks:
      - evaultz_net

  frontend:
    build:
      context: ./frontend/evaultzweb
      dockerfile: Dockerfile.dev
    container_name: evaultz-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:8082
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      WATCHPACK_POLLING_INTERVAL: 500
      NEXT_WEBPACK_USEPOLLING: "true"
    volumes:
      - frontend_node_modules:/app/node_modules
      - ./frontend/evaultzweb:/app
    networks:
      - evaultz_net
    depends_on:
      - backend

volumes:
  backend_tmp:
  frontend_node_modules:
  go_cache:
  db_data: # ✅ added for Postgres persistence

networks:
  evaultz_net:
    driver: bridge
